export const ACCESS_TOKEN = 'ACCESS_TOKEN'
export const PATH = 'PATH'
export const STORE = 'STORE'
export const JWT = 'JWT'
export const ACCOUNT_ID = 'ACCOUNT_ID'
export const USERNAME = 'USERNAME'
export const EMAIL = 'EMAIL'
export const ROLES = 'ROLES'